### PR TITLE
Update python libraries to newer versions

### PR DESCRIPTION
**Pull request by ubajze**
I have an issue with the `grafana-chatops` plugin, which has the `schema-enforcer` lib as a dependency. In particular, the problem is with the `ruamel.yaml` package. So, I want to upgrade packages to newer versions.

### CODE REVIEW

**Comment by ubajze** [comment]
Can we release a new version after/if this PR is merged.

**Comment by PhillSimonds** [comment]
Yeah absolutely. It looks like we're failing on pylint -- I'll update the code to make it pass pylint then we can get a merge + release.

**Comment by dgarros** [comment]
I opened another PR #116 that is fixing few more things, I think we should close this one in favor of the other one

**Comment by PhillSimonds** [comment]
@ubajze Are you good with me closing this in favor of #116 ?

**Comment by ubajze** [comment]
Closing this PR.

**Pull request closed without merging**
