### PR TITLE
[ISSUE-156] - Add support for jsonschema version ^4.18

### PR DESCRIPTION
**Pull request by PhillSimonds**
JSONSchema version 4.18 includes some breaking changes. Namely:

- It removed the location of the draft7 schema doc
- It requires python3.8, deprecating support of 3.7
- It modifies the API for the format checkers and the RefResolver.

This PR updates the repository to account for all of the above spare the RefResolver, which I will account for in a separate PR. It also updates the lock file to incorporate the latest versions of packages within the constraints defined in pyproject.toml.

### CODE REVIEW

**Comment by PhillSimonds** [comment]
@glennmatthews -- I wasn't quite sure how to handle the versioning here. I think it needs a significant bump because we have to strip out support for python 3.7 in order to support jsonschema 4.18. `4.17.x` is installed if python 3.7 is used (instead of 4.18) -- but there are some significant differences in the way the jsonschema api is called in 4.18 vs 4.17, so I figured it would be best to mandate the use of 4.18 or greater so we don't have to deal with those. That may be too restrictive though.

**Comment by glennmatthews** [comment]
Definitely should be fine to drop 3.7 support at this point.

It would be *best* if we could support earlier versions of `jsonschema` for at least a while so that this won't have to be a hard cut-over (it'll be problematic with Nautobot for instance given that it's currently pinning to `<4.18` due to this issue)... any thoughts on how difficult that would be?

**Comment by PhillSimonds** [comment]
OK looks like all the ways in which I've modified the API calls to JSONSchema per this PR were already available in 4.6; so 4.6 is still working in local builds. I'm going to take the min version back down to ^4.6

It looks like deprecation of the `ResolverRef` in favor of the referencing library happened right in 4.18 -- so no need to whip that into the fix. We're getting deprecation warnings on that, but I think the referencing library implementation will only support 4.18+ -- so it should probably require a major version bump of schema-enforcer. As such, I'll put that into a different release.

**Review by glennmatthews — APPROVED** [review]

**Comment by glennmatthews** [comment]
Actually, given that `jsonschema` doesn't seem to exactly follow semver, should we add an upper bound of 4.18 for now?

**Comment by PhillSimonds** [comment]
We can, but I think it *is* actually following semver. The issue we found is they moved a file that had the version7 schema json data in it. We were imported this data from inside the library (which I think is probably not a best practice). They technically didn't change the API in a breaking way with the move to 4.18, just the location of internal files.

**Pull request merged**
