### PR TITLE
Prep for 1.1.4 release

### LINKED ISSUE #130: Add hostname validation check
### Environment
* Python version:  3.9.11
* schema-enforcer version:  1.1.4

### Expected Behavior

When a schema is defined with a string type of `hostname`, I expected the following values to fail validation checks:

- "this_is_not_a_valid_hostname"
- "ntc@123.com"

### Observed Behavior

Validation checks succeed.

### Steps to Reproduce
1. Create a schema with the following definition

```yaml
---
$schema: "http://json-schema.org/draft-07/schema#"
$id: "schemas/incorrect_hostname_format"
description: "DNS Server Configuration schema."
type: "object"
properties:
  dns_servers:
    type: "array"
    items:
      type: "object"
      properties:
        hostname:
          type: "string"
          format: "hostname"
        required:
          - "hostname"
    uniqueItems: true
required:
  - "dns_servers"
```

2. Define a data file of the following format.

```
---
dns_servers:
  - hostname: "ntc@ntc.com"
```

3. Run schema enforcer to validate the data file and observe it passes validation checks where it should fail.

### PR DESCRIPTION
**Pull request by PhillSimonds**
This PR preps for v1.1.4 release. It updates dependencies such that jsonschema v4.4 or greater is required.

Fixes #130

### CODE REVIEW

**Comment by glennmatthews** [comment]
Is the hostname validation thing a bug of some sort? I hate to just remove a test because it started failing. :-)

**Comment by PhillSimonds** [comment]
Yeah It's with the `draft7_format_checker` which is imported from `jsonschema`. It looks like, in the newer version of jsonschema, it's not correctly enforcing the `hostname` format. I created #130 to look into it and figure out why (change to jsonschema that's expected, bug that needs to be fixed in jsonschema library) and how we might amend (add a format checker on our side that checks it, put bug fix into jsonschema repo...etc).

**Comment by ubajze** [comment]
I tried to add Nautobot 1.3.5 to the poetry project and it seems that dependencies are successfully resolved. For me, this looks good.

**Review by ubajze — APPROVED** [review]

**Comment by glennmatthews** [comment]
See #132 as a pre-requisite for merging this PR.

**Comment by PhillSimonds** [comment]
> See #132 as a pre-requisite for merging this PR.

Thanks for #132 Glenn :).

**Review by glennmatthews — APPROVED** [review]

**Comment by ubajze** [comment]
@PhillSimonds Can we merge this and release a new version?

**Pull request merged**
